version: "3"
services:
  postgresDb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_DATABASE: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"